// Germany
export const locale = {
  lang: "mn",
  data: {
    LAMBDA_LLC: "Ламбда ХХК",
    DASHBOARD: {
      SALES: "Борлуулалтууд",
      BY_AMOUNT: "Дүнгээр",
      BY_COUNT: "Тоогоор",
      DAILY: "Өдрөөр",
      MONTHLY: "Сараар",
      SALES_BY_PRODUCT: "Бүтээгдэхүүнээр",
      SALES_BY_PAYMENT: "Төлбөрийн төрлөөр",
      TODAY: "Өнөөдөр",
      YESTERDAY: "Өчигдөр",
      LAST_7_DAYS: "7 хоног",
      LAST_30_DAYS: "30 хоног",
      LAST_90_DAYS: "90 хоног",
      PERFORMANCE_BY_MERCHANT: "Мерчант гүйцэтгэл",
      PERFORMANCE_BY_MERCHANT_CARD: "Мерчант гүйцэтгэл: Карт",
    },
    MODULE: {
      DASHBOARD: "Хянах самбар",
      MERCHANT: "Мерчант",
      TERMINALS: "Терминал",
      DEVICES: "Төхөөрөмж",
      SALES: "Борлуулалт",
      NOZZLE: "Хошуу",
      USERS: "Ажилчидын бүртгэл",
      ADMIN_USER: "Админ хэрэглэгч",
      TYPE: "Төрөл",
      BRANCH: "Салбар",
      VERSION: "Хувилбар",
      UPDATE: "Шинэчлэлт",
      ISSUE: "Санал гомдол",
      PENDING_CHANGE: "Хүлээгдэж буй өөрчлөлт",
      UMONEY: "UMoney цэнэглэлт",
      TELECOM: "Телеком цэнэглэлт",
      VAS_TERMINAL: "Нэмэлт үйлчилгээний терминал",
      VAS_SETTLEMENT: "Нэмэлт үйлчилгээний нэгтгэл",
      PENDING_DEPOSIT: "Хүлээгдэж буй цэнэглэлт",
      PAPER_ORDER: "Цаасны захиалга",
      PAYMENT_SPLIT: "Төлбөр хуваалт",
      PAYMENT_RECEIVERS: "Төлбөр хүлээн авагчид",
      SPLITS: "Хуваалтууд",
      PAYMENT_SETTLEMENTS: "Хуваалтын нэгтгэлүүд",
      BILL: "Билл",
      BILL_PAYMENT: "Билл төлөлт",
      LOAN_PAYMENT: "Зээл төлөлт",
      BILLER: "Биллерүүд",
      SETTINGS: "Тохиргоо",
      TAG: "Tag",
      CARD_BIN: "Карт Bin",
      CATEGORY: "Ангилал",
      PRODUCT: "Бүтээгдэхүүн",
      INVENTORY: "Бүтээгдэхүүн",
      FEE: "Мерчант Төлбөр",
      VAT_RECEIPT: "НӨАТ-ын баримт",
      TRANSACTION: "Гүйлгээнүүд",
      BANK_SETTLEMENT: "Банк нэгтгэл",
      MERCHANT_SETTLEMENT: "Мерчант нэгтгэл",
      THIRD_PARTY: "Гуравдагч байгууллага",
      CARD_REVERSALS: "Картын буцаалт",
      MDR: "MDR",
    },
    SHARED: {
      ID: "ID",
      MERCHANT: "Мерчант",
      TERMINAL: "Терминал",
      EMPLOYEE: "Ажилтан",
      NAME: "Нэр",
      MOBILE: "Утас",
      REMARK: "Тайлбар",
      STATUS: "Төлөв",
      CODE: "Код",
      CITY: "Хот",
      ADDRESS: "Хаяг",
      CREATED_AT: "Үүссэн",
      DESCRIPTION: "Тайлбар",
      ACTIVITY: "Өөрчлөлтүүд",
      ROLES: "Эрхийн түвшин",
      LANGUAGE: "Хэл",
      SIGN_OUT: "Гарах",
      TAG: "Tag",
      ISADMIN: "Админ",
      DEVICE: "UDID",
      MERCHANT_ID: "Мерч ID",
      TERMINAL_ID: "Терминал ID",
      TYPE: "Төрөл",
      CREATED_BY: "Үүсгэгч",
      START_DATE: "Эхлэх огноо",
      END_DATE: "Дуусах огноо",
      UPDATED_AT: "Шинэчилсэн",
      SP_UPDATE: "SP шинэчлэл",
      ENTITY_TYPE: "Entity Type",
      ENTITY_ID: "Entity ID",
      AMOUNT: "Дүн",
      UTERMINAL_ID: "U Терминал №",
      CARD_NO: "Картын №",
      CARD_PRE_POST_BALANCE: "Карт цэнэглэлтийн өмнө/дараа",
      WALLET_PRE_POST_BALANCE: "Хэтэвч цэнэглэлтийн өмнө/дараа",
      PAYMENT_TYPE: "Төл-хэрэгсэл",
      WALLET_TRANSACTION_TYPE: "Хэтэвчний гүйлгээний төрөл",
      SERVICE: "Үйлчилгээ",
      QTY: "Тоо",
      REFERRAL_CODE: "Гүйлгээний код",
      DATE: "Огноо",
      ADDITIONAL_SERVICE: "Нэмэлт үйлчилгээ",
      VSAMID: "VSAMID",
      AUTHENTICATION_ID: "Authentication ID",
      DEVICE_ID: "Төхөөрөмж ID(UDID)",
      DEALER_PHONE: "Дилер дугаар",
      DEALER_CODE: "Дилер код",
      DELIVERY_PHONE_ADDRESS: "Хүргэлтийн утас/хаяг",
      DELIVERED_AT: "Хүргэсэн огноо",
      MERCHANT_TERMINAL: "Мерчант/Терминал",
      DATE_FILTER_TYPE: "Хугацааны төрөл",
      BANK_ACCOUNT: "Данс",
      BANK_ADD: "Данс нэмэх",
      BANK_ACCOUNT_NAME: "Дансны нэр",
      BANK: "Банк",
      CREATED: "Үүсгэсэн",
      TRANSFER_DESC: "Гүйлгээний утга",
      MODULE: "Модуль",
      MANAGE: "Өөрчлөх",
      VIEW: "Харах",
      SCHEDULE_AT: "Хуваарьт өдөр",
      PAY: "Төлөх",
      PAID_AMOUNT: "Төлсөн дүн",
      DEDUCT_AT: "Суутгасан огноо",
      TRANSFER_START: "Шилжүүлэг эхлүүлэх",
      BANK_FEE: "Шимтгэл",
      EMAIL: "И-мэйл",
      TITLE: "Гарчиг",
      CATEGORY: "Ангилал",
      PRODUCT: "Бүтээгдэхүүн",
      NO: "Үгүй",
      YES: "Тийм",
      NAMEDBA: "Нэр dba",
      DISTRICT: "Дүүрэг",
      INFO: "Мэдээлэл",
      SORT: "Эрэмблэх",
      REASON: "Шалтгаан",
      TAX_PAYER_ID_FULL: "Татвар төлөгчийн дугаар (Бүтэн)",
      VAT: "НӨАТ",
      SENT_AT: "Илгээсэн огноо",
      PAYMENTS: "Төлбөрүүд",
      TOTAL_AMOUNT: "Нийт дүн",
      TOTAL: "Нийт",
      PRODUCTS: "Бүтээгдэхүүн",
      FEE: "Шимтгэл",
      FACEBOOK: "Facebook",
      INSTAGRAM: "Instagram",
      WEBSITE: "Вэб сайт",
      PRE_BALANCE: "Өмнөх дүн",
      POST_BALANCE: "Дараах дүн",
      CREDIT: "Зарлага",
      DEBIT: "Орлого",
      INTENT: "Төрөл",
      CARD: "Карт",
      PAYMENT: "Төлөлт",
      COUNT: "Тоо",
      MAIN: "Үндсэн мэдээлэл",
      DETAIL: "Дэлгэрэнгүй",
      PAYMENT_TRANSFERRED: "Шилж-дүн",
      REGISTRATION: "Бүртгэл",
      TRANSACTION_SETTLEMENT: "Гүйлгээ нэгтгэл",
      DEDUCTION: "Суутгал",
      OTHER: "Бусад",
    },
    ACTION: {
      ACTION: "Үйлдэл",
      EDIT: "Засах",
      ADD: "Нэмэх",
      SEARCH: "Хайх",
      DELETE: "Устгах",
      ACTIVATE: "Идэвхжүүлэх",
      SAVE: "Хадгалах",
      BACK: "Буцах",
      CONTINUE: "Үргэлжлүүлэх",
      REMOVE: "устгах",
      DOWNLOAD: "Татах",
      SAVED: "Амжилттай хадгалагдлаа",
      DELETED: "Амжилттай устгалаа",
      CANCEL: "Болих",
      SELECT: "Сонгох",
      END: "Дуусгах",
      CHANGE: "Өөрчлөлт",
      CLEAR: "Цэвэрлэх",
      APPROVE: "Зөвшөөрөх",
      PENDING_ADDED: "Хүлээгдэж буй өөрчлөлт нэмэгдлээ",
      SAVE_SYNC: "Хадгалах & Илгээх",
      DELIVERED: "Хүргэлт хийгдсэн",
      CLOSE: "Хаах",
      INACTIVE: "Идэвхгүй болгох",
    },
    MERCHANT: {
      MERCHANTS: "Мерчантууд",
      DETAIL: "Дэлгэрэнгүй",
      LIST: "Мерчантын жагсаалт",
      ADD: "Мерчант нэмэх",
      EDIT: "Мерчант засах",
      OFFLINE_MODE: "Оффлайн горим",
      PRINT_NON_VAT: "НӨАТ-гүй баримт хэвлэх",
      ADDED: "Мерчант амжилттай нэмэгдлээ",
      UPDATED: "Мерчант амжилттай хадгалагдлаа",
      TENANT: "Тенант",
      CONTACT: "Холбоо барих",
      FILE: "Бичиг баримт",
      DELETE: "Мерчант устгах",
      MCCCATEGORY: "MCC Ангилал",
      MCC: "MCC",
      REGISTERNO: "Регистр",
      EMPLOYEE: "Х/ажилтан",
      CONNECTED: "Нэмэлт мэдээлэл",
      LIMITFEE_ENABLED: "Limit fee",
      EBARIMTFEE_ENABLED: "Ebarimt fee",
      ADDITIONAL: "Нэмэлт Мэдээлэл",
      MAIN: "Үндсэн Мэдээлэл",
      CHANGE_BANK_ACCOUNT: "Данс солих",
      BRANCH: "Салбар",
      BRANCH_ADD: "Салбар Нэмэх",
    },
    TERMINAL: {
      TERMINALS: "Терминалууд",
      DETAIL: "Терминал дэлгэрэнгүй",
      LIST: "Терминалууд",
      ADD: "Терминал нэмэх",
      EDIT: "Терминал засах",
      UDID: "UDID",
      NEWUDID: "Шинэ Сериал дугаар",
      BANKMID: "Банк MID",
      BANKTID: "Банк TID",
      SOCIALTID: "Сошиал TID",
      PAYMENT_SETTINGS: "Төлбөрийн тохиргоо",
      PAYMENT_IDS: "Social TID",
      AUTO_SETTLEMENT: "Авто өндөрлөгөө",
      BIN_PREFIX: "Bin prefix",
      ECR_MODE: "Кассын холболт",
      ECR_CLOSABLE: "Кассын холболтоос гарах",
      VAT_ENABLED: "НӨАТ идэвхжсэн",
      TAX_DISTRICT: "Татварын дүүрэг",
      TAX_SUB_DISTRICT: "Татварын дэд дүүрэг",
      TAX_PAYER_ID: "Т/Төлөгчийн дугаар",
      TAX_PAYER_NAME: "Т/Төлөгчийн нэр",
      TIN: "Татвар төлөгчийн дугаар (TIN)",
      IS_VAT_PAYER: "НӨАТ төлөгч эсэх",
      PAPER_PHONE: "Цаас утас",
      PAPER_ADDRESS: "Цаас хаяг",
      VAS_ENABLED: "Нэмэлт үйлчилгээ",
      GATEWAY: "Gateway",
      VAT_SETTINGS: "НӨАТ тохиргоо",
      CITY_PAYER: "City payer",
      TID: "TID",
      SOCIALTID_GENERATE: "Social Tid үүсгэх",
    },
    USER: {
      USERS: "Ажилтан",
      DETAIL: "Ажилтаны дэлгэрэнгүй",
      LIST: "Холбоо барих",
      ADD: "Ажилтан нэмэх",
      CHANGE_PASSWORD: "Нууц үг солих",
      EDIT: "Ажилтан засах",
      ROLE: "Эрхийн түвшин",
      USERNAME: "Нэвтрэх нэр",
      EMPLOYEE_CARD: "Ажилтны карт",
      REF: "Дугаар",
      PASSWORD: "Нууц үг",
      NEW_PASSWORD: "Шинэ нууц үг",
      REPEAT_PASSWORD: "Нууц үг давтах",
      POSITION: "Албан байр",
    },
    ADMIN_USER: {
      ADMIN_USERS: "Админ хэрэглэгчид",
      DETAIL: "Админ хэрэглэгчийн дэлгэрэнгүй",
      LIST: "Админ хэрэглэгчийн жагсаалт",
      ADD: "Хэрэглэгч нэмэх",
      EDIT: "Хэрэглэгч засах",
    },
    LIST_MODE: {
      TABLE: "Жагсаалт",
      MAP: "Газрын зураг",
    },
    DEVICE: {
      DETAIL: "Төхөөрөмжийн дэлгэрэнгүй",
      LIST: "Төхөөрөмжүүд",
      MODEL: "Загвар",
      ADD: "Төхөөрөмж нэмэх",
      EDIT: "Төхөөрөмж засах",
      TOTAL_DEVICE: "Нийт төхөөрөмж",
      BATCH_UPLOAD: "Багц нэмэх",
      WAREHOUSE: "Агуулах нэмэх",
      SAMPLE: "Sample",
      ASSIGN_USER: "Хэрэглэгч холбох",
      FIX: "Засвар",
      CEASE: "Актлах",
      SOLD_AMOUNT: "Үнийн дүн",
      SOLD: "Зарагдсан",
      SOLD_AT: "Зарагдсан огноо",
      SIM_CARD: "SIM карт",
      BROKEN: "Эвдэрсэн",
      PULL: "Татах",
      BROKEN_RECEIVED: "Эвдэрсэн агуулахад",
      SUCCESSFULL_CEASE: "Актлагдсан",
      ISSOLDABLE: "Зарагдаж болох",
      IS_DEVELOPMENT: "Хөгжүүлэлт эсэх",
      OPERATOR: "Үүрэн холбоо",
      CHANGE: "Төхөөрөмж нэмэх",
    },
    VERSION: {
      ADD: "Хувилбар нэмэх",
      VERSION: "Хувилбар",
      MODEL: "Загвар",
      LIST: "Хувилбарын жагсаалт",
      RELEASE_NOTE: "Дэлгэрэнгүй",
      UDID: "UDID",
    },
    UPDATE: {
      ADD: "Шинэчлэлтийн нэмэх",
      LIST: "Шинэчлэлтийн жагсаалт",
      TYPE: "Шинэчлэлийн Төрөл",
    },
    ISSUE: {
      ADD: "Санал гомдол нэмэх",
      LIST: "Санал гомдол жагсаалт",
      SOLUTION: "Шийдэл",
      SOLVED_AT: "Шийдвэрлэгдсэн огноо",
    },
    UMONEY: {
      UMONEY: "Umoney",
      LIST: "Umoney жагсаалт",
      UTERMINAL_ID: "U Терминал",
    },
    TELECOM: {
      TELECOM: "Телеком",
      LIST: "Телеком жагсаалт",
      MOBILE_CONTRACT_NO: "Утас/Гэрээ №",
      EXTRA_DETAIL: "Нэмэлт мэдээлэл",
      RESPONSE: "Телеком хариу",
    },
    VAS_TERMINAL: {
      LIST: "Терминал жагсаалт",
      DETAIL: "Терминал дэлгэрэнгүй",
      WALLET_BALANCE: "Хэтэвчний үлдэгдэл",
      UTERMINAL: "U Терминал",
      USTATUS: "UMONEY төлөв",
      TSTATUS: "Скайтэл төлөв",
      DEALER_CODE: "Скайтэл код",
      EXTRA_SERVICE: "Нэмэлт үйлчилгээ",
      EZTERMINAL_ID: "EZ Терминал ID",
      WALLET_TRANSACTIONS: "Хэтэвчний түүх",
      WALLET_TOPUP: "Хэтэвч цэнэглэх",
    },
    VAS_SETTLEMENT: {
      LIST: "Нэгтгэлийн жагсаалт",
      SERVICE: "Үйлчилгээ",
      CONNECTION_DATE: "Хам/хугацаа",
      SETTLEMENT_DATE: "Нэгтгэл",
      SENDER: "Илгээгч",
      RECEIVER: "Хүлээн авагч",
      TRANSACTION_DESCRIPTION: "Гүйлгээний утга",
      TRANSACTION_RESPONSE: "Гүйл/хариу",
      TRANSFER_DATE: "Шилжсэн",
      MERCHANT_REWARDS: "Мерчант сарын урамшуулал",
      TENANT_REWARDS: "Тенант сарын урамшуулал",
      RETRY_TRANSACTION: "Шилжүүлэг дахин эхлүүлэх",
      START_SETTLEMENT: "Нэгтгэл эхлүүлэх",
      BANK_TRANSFER: "Шилжүүлэг эхлэх",
      REWARDS: "Урамшуулал",
    },
    VAS_TRANSACTION: {
      TRANSACTION: "Хэтэвч гүйлгээ",
    },
    PENDING_DEPOSIT: {
      LIST: "Хүлээгдэж буй цэнэглэлтийн жагсаалт",
    },
    PAPER_ORDER: {
      ADD: "Захиалга нэмэх",
      LIST: "Цаасны захиалгууд",
      CHANNEL: "Суваг",
      PAPER_QTY: "Цаасны тоо",
      DELIVERY_NUMBER1: "Хүргэлтийн утас 1",
      DELIVERY_NUMBER2: "Хүргэлтийн утас 1",
      DELIVERY_ADDRESS: "Хүргэлтийн хаяг",
    },
    PAYMENT: {
      RECEIVER: "Төлбөр хүлээн авагч",
      BANKACCOUNT: "Данс",
      BANKACCOUNTNAME: "Данс нэр",
      BANK: "Банк",
      RECEIVER_LIST: "Төлбөр хүлээн авагчид",
      RECEIVER_ADD: "Хүлээн авагч нэмэх",
      RECEIVER_ADDED: "Төлбөр хүлээн авагч амжилттай нэмэгдлээ",
      SPLITS: "Төлбөр хуваалтууд",
      SPLIT_AMOUNT: "Хуваасан дүн",
      REMARK: "Хуваалтын тайлбар",
      REFERENCE: "Лавлах код",
      SETTLEMENT_LIST: "Төлбөр хуваалтын нэгтгэлүүд",
      RECEIVER_ID: "Хүлээн авагч ID",
      RECEIVER_ID_NAME: "Хүлээн авагч ID/Нэр",
      TOTAL: "Нийт",
      TOTAL_AMOUNT: "Нэгтгэл дүн",
      TRANSFER_DESC: "Гүйлгээний утга",
      TRANSFER_RES: "Гүйл/хариу",
      TRANSFER_DATE: "Шилжүүлсэн огноо",
      CREATED: "Үүсгэсэн",
      RECEIVER_DELETE: "Төлбөр хүлээн авагч устгах",
      RECEIVER_ACTIVATE: "Төлбөр хүлээн авагч идэвхжүүлэх",
      TRANSFER_AT: "Шилжүүлсэн огноо",
      SETTLEMENT_DETAIL: "Төлбөр хуваалтын нэгтгэлийн дэлгэрэнгүй",
      TERMINAL_ID: "Терминал ID",
    },
    BILL: {
      PAYMENTS_LIST: "Билл төлөлтүүд",
      BILLER: "Биллер",
      BILLER_LIST: "Биллерийн жагсаалт",
      REF: "Билл дугаар",
      PAYMENT_DETAIL: "Билл төлөлтийн дэлгэрэнгүй",
      BILLER_ADD: "Биллер нэмэх",
      BILLER_DELETE: "Биллер устгах",
      BILLER_ACTIVATE: "Биллер идэвхжүүлэх",
      ID: "Билл ID",
      BILLER_ID: "Биллер ID",
      PAYMENT_DOWNLOAD: "Билл төлөлт татах",
    },
    LOAN: {
      REF: "Зээлийн дугаар",
      PAYMENTS_LIST: "Зээл төлөлтүүд",
      LIST_DOWNLOAD: "Зээлийн жагсаалт татах",
    },
    CONTACT: {
      LIST: "Холбоо барих / хэрэглэгч",
      ADD: "Холбоо барих хүн нэмэх",
      RELATION: "Хэн болох",
      EMERGENCY: "Яаралтай",
    },
    FILE: {
      LIST: "Бичиг баримтын жагсаалт",
      NAME: "Файлын нэр",
    },
    CARD: {
      LIST: "Карт Bin жагсаалт",
      START: "Эхлэл",
      END: "Төгсгөл",
      ADD: "Карт Bin нэмэх",
    },
    TAG: {
      LIST: "Tag жагсаалт",
      ADD: "Tag нэмэх",
    },
    PRODUCT: {
      LIST: "Бүтээгдэхүүний жагсаалт",
      MEASURE_UNIT: "Хэмжих нэгж",
      VAT_TYPE: "Vat төрөл",
      TAX_PRODUCT_CODE: "Tax бүтээгдэхүүн код",
      CITY_TAX: "City такс",
      BAR_CODE_TYPE: "Бар код төрөл",
      BAR_CODE: "Бар код",
      ADD: "Бүтээгдэхүүн нэмэх",
      PRICE: "Үнэ",
    },
    CATEGORY: {
      LIST: "Ангилалын жагсаалт",
      NAME: "Ангилалын нэр",
      ADD: "Ангилал нэмэх",
    },
    MERCHANT_FEE: {
      LIST: "Мерчант төлбөрүүд",
      BATCH_ADD: "Төлбөр үүсгэх",
      AMOUNT: "Төлбөрийн дүн",
      SPLIT_DAYS: "Хуваалт",
      BETWEEN_DATE: "Хоног",
      CHARGE_DATE: "Төлбөр идэвхжих огноо",
      SETTLEMENT: "Нэгтгэл",
      SETTLEMENT_AT: "Нэгтгэл огноо",
      CLOSEDESCRIPTION: "Хаасан тайлбар",
      ADD_SEAL: "Битүүмж нэмэх",
      PAID: "Төлсөн",
    },
    RECEIPT: {
      BILL_ID: "Билл ID",
      CITY_TAX: "City tax",
      VAT: "НӨАТ-ын баримт",
    },
    TRANSACTION: {
      LIST: "Гүйлгээний түүх",
      SETTLEMENTNO: "Settlement №",
      TRACENO: "Trace №",
      BATCHNO: "Batch №",
      TYPE: "Гүйлгээний төрөл",
      CARD_NUMBER: "Картын дугаар",
      NUMBER: "Гүйлгээний дугаар",
      AMOUNT: "Гүйлгээний дүн",
      REFNO: "RefNo",
      APPROVE_CODE: "Approve Code",
      MASKED_PAN: "Masked Pan",
      EBARIMT_LOTTERY: "EBARIMT Lottery",
      EBARIMT_BILL_ID: "EBARIMT Bill ID",
      DETAIL: "Гүйлгээний дэлгэрэнгүй",
      AT: "Огноо",
      BANK_SETTLEMENT_AT: "Банк нэгтгэл",
      VAT_RECEIPT_ID: "Vat Receipt ID",
    },
    BANK_SETTLEMENT: {
      LIST: "Банк нэгтгэлүүд",
      DETAIL: "Банк нэгтгэл дэлгэрэнгүй",
      DISPLAY_COUNT: "Display Count",
      DISPLAY_AMOUNT: "Display Amount",
      ID: "Банкны нэгтгэл ID",
      NO: "Тооцооны дугаар",
      DATE: "Тооцооны огноо",
      REQUEST_AT: "Хүсэлт илгээсэн огноо",
      TRIGGERED_BY: "Илгээгч",
      PAYMENT: "Төлбөр",
      AMOUNT: "Дүн/Нэгтгэл дүн",
    },
    MERCHANT_SETTLEMENT: {
      DETAIL: "Мерчант нэгтгэл дэлгэрэнгүй",
      LIST: "Мерчант нэгтгэлүүд",
      ID: "Мерчант нэгтгэл ID",
      ERP_RESPONSE: "ERP хүсэлт",
      TRANSFERED_AT: "Шилжүүлсэн огноо",
      TRANSFERED_AMOUNT: "Шилжүүлсэн дүн",
      FEE: "Шимтгэл",
      AMOUNT: "Дүн/Шилжүүлсэн дүн",
      FEE_AMOUNT: "Шимтгэл + Бэлэн /Суутгал",
    },
    THIRD_PARTY: {
      NAME: "Нэр",
      STATUS: "Төлөв",
      IP: "IPS",
      TOKEN: "Token",
      MAIN: "Жагсаалт",
      ADD: "Нэмэх",
      CREATED_AT: "Үүссэн",
      CREATE_TOKEN: "Token Үүсгэх",
      COPY: "Хуулах",
      COPY_SUCCESS: "Амжилттай хууллаа!",
      SUCCESS: "Амжилттай!",
    },
    CARD_REVERSALS: {
      MAIN: "Жагсаалт",
      DELETE: "Устгах",
      STATUS: "Төлөв",
      BANK_MID: "Банк MID",
      BANK_TID: "Банк TID",
      TRACENO: "Trace No",
      START_DATE: "Эхэлсэн",
      END_DATE: "Дууссан",
      AMOUNT: "Дүн",
      RETRY_TIMES: "Retry Times",
      CREATED_AT: "Үүссэн",
      SUCCEED_DELETED: "Амжилттай устгалаа!",
      MASKEDPAN: "MaskedPAN",
    },
    CARD_ZONE: {
      RESYNC: "Card Zone Resync",
      SYNCED_AT: "Synced at",
    },
    MDR: {
      LIST: "MDR жагсаалт",
      CARD_ZONE_MDR: "Card Zone MDR",
      SOCIALPAY_MDR: "Socialpay MDR",
    },
    INPUT: { PLACEHOLDER: "{{value}}" },
  },
};
